version: "3.9"
services:
  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "potgres"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - /Logs/:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  prometheus:
    build: Metrics/
    ports:
      - "9090:9090"